apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: reloop
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres-init.yaml
  - postgres.yaml
  - mongo.yaml
  - redis.yaml
  - storage.yaml
  - apps.yaml
