apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-service-uploads
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-service-review-uploads
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-service-private-evidence
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-service-private-attachments
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
